--- #YAML:1.0
name:                HTML-SimpleLinkExtor
version:             1.16
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    HTML::LinkExtor:               1.28
    LWP::Simple:                   0
    URI:                           1.09
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
