--- #YAML:1.0
name:                HTML-SimpleLinkExtor
version:             1.21_01
abstract:            Extract links from HTML
license:             perl
author:              
    - brian d foy <bdfoy@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    HTML::LinkExtor:               1.28
    LWP::UserAgent:                0
    Test::Output:                  0
    URI:                           1.09
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
